### ISSUE TITLE
Issues adding Whitelist

### ISSUE THREAD

**Issue by notorioustubze** [hg1978/AdGuard-Home-Whitelist#4]
Hello, I'd very much like to add your whitelist to my Adguard home setup however when I try to add it I get an error message "Error: control/filter/add_url couldn't fetch filter from URL data is HTML, not plain text 400" Are you able to advise how I go about adding your list? Thanks in advance!

**Comment by hg1978** [comment]
Hi, you need to use that URL:
https://raw.githubusercontent.com/hg1978/AdGuard-Home-Whitelist/master/whitelist.txt

Should work

**Comment by notorioustubze** [comment]
Worked perfectly not quite sure what I was entering before :) Thank you!

**Comment by hg1978** [comment]
Perfect!
